[package]

version = "0.1.1"

category = "isaaclab"
readme  = "README.md"

title = "DiffAero UAV Extension"
author = "DiffAero Team"
maintainer = "DiffAero Team"
description="UAV platform capabilities, dynamics models, and adapters for DiffAero on IsaacLab"
repository = "https://github.com/diffaero/diffaero-lab"
keywords = ["diffaero", "isaaclab", "drone", "uav", "quadrotor"]

[dependencies]
"isaaclab" = {}
"diffaero_common" = {}

[[python.module]]
name = "diffaero_uav"

[isaac_lab_settings]
